// Pure-Node tests for the extractors that don't need Electron.
const test = require("node:test");
const assert = require("node:assert/strict");
const zlib = require("node:zlib");
const zip = require("../src/main/extract/zipfile");
const mesh = require("../src/main/extract/mesh");
const text = require("../src/main/extract/text");

function makeZip(entries) {
  // stored + deflated entries, minimal writer for tests
  const parts = [], central = [];
  let off = 0;
  for (const [name, data, method] of entries) {
    const nameB = Buffer.from(name);
    const comp = method === 8 ? zlib.deflateRawSync(data) : method === 93 ? zlib.zstdCompressSync(data) : data;
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0); lh.writeUInt16LE(method, 8); lh.writeUInt32LE(comp.length, 18); lh.writeUInt32LE(data.length, 22); lh.writeUInt16LE(nameB.length, 26);
    parts.push(lh, nameB, comp);
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0); ch.writeUInt16LE(method, 10); ch.writeUInt32LE(comp.length, 20); ch.writeUInt32LE(data.length, 24); ch.writeUInt16LE(nameB.length, 28); ch.writeUInt32LE(off, 42);
    central.push(ch, nameB);
    off += 30 + nameB.length + comp.length;
  }
  const cd = Buffer.concat(central);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); eocd.writeUInt16LE(entries.length, 8); eocd.writeUInt16LE(entries.length, 10); eocd.writeUInt32LE(cd.length, 12); eocd.writeUInt32LE(off, 16);
  return Buffer.concat([...parts, cd, eocd]);
}

test("zipfile reads stored, deflated and zstd entries", () => {
  const buf = makeZip([["a.txt", Buffer.from("hello"), 0], ["b.txt", Buffer.from("world".repeat(50)), 8], ["c.txt", Buffer.from("zstd!".repeat(20)), 93]]);
  const es = zip.entries(buf);
  assert.deepEqual(es.map((e) => e.name), ["a.txt", "b.txt", "c.txt"]);
  assert.equal(zip.read(buf, es[0]).toString(), "hello");
  assert.equal(zip.read(buf, es[1]).toString(), "world".repeat(50));
  assert.equal(zip.read(buf, es[2]).toString(), "zstd!".repeat(20));
  assert.equal(zip.find(buf, (e) => e.name.endsWith("b.txt")).length, 250);
});

test("binary STL: triangle count, bounding box and volume of a unit cube", () => {
  const tris = [];
  const quad = (a, b, c, d) => { tris.push([a, b, c], [a, c, d]); };
  const p = (x, y, z) => [x, y, z];
  quad(p(0,0,0), p(0,1,0), p(1,1,0), p(1,0,0)); // bottom (normal -z)
  quad(p(0,0,1), p(1,0,1), p(1,1,1), p(0,1,1)); // top
  quad(p(0,0,0), p(1,0,0), p(1,0,1), p(0,0,1)); // front
  quad(p(1,0,0), p(1,1,0), p(1,1,1), p(1,0,1)); // right
  quad(p(1,1,0), p(0,1,0), p(0,1,1), p(1,1,1)); // back
  quad(p(0,1,0), p(0,0,0), p(0,0,1), p(0,1,1)); // left
  const buf = Buffer.alloc(84 + tris.length * 50);
  buf.writeUInt32LE(tris.length, 80);
  tris.forEach((t, i) => { let o = 84 + i * 50 + 12; for (const v of t) { buf.writeFloatLE(v[0], o); buf.writeFloatLE(v[1], o + 4); buf.writeFloatLE(v[2], o + 8); o += 12; } });
  const m = mesh.stl(buf);
  assert.equal(m.Triangles, 12);
  assert.equal(m["Size X"], 1);
  assert.equal(m["Size Z"], 1);
  assert.equal(m["Volume (mm³)"], 1);
});

test("ASCII STL parses", () => {
  const s = `solid t\nfacet normal 0 0 1\nouter loop\nvertex 0 0 0\nvertex 2 0 0\nvertex 0 3 0\nendloop\nendfacet\nendsolid t\n`;
  const m = mesh.stl(Buffer.from(s));
  assert.equal(m.Format, "ASCII STL");
  assert.equal(m.Triangles, 1);
  assert.equal(m["Size Y"], 3);
});

test("STEP header fields", () => {
  const s = `ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('STEP AP214'),'2;1');\nFILE_NAME('x.step','2026-01-01T00:00:00',('Joe'),('AxialForge'),'pre','SolidWorks 2024','');\nFILE_SCHEMA(('AUTOMOTIVE_DESIGN { 1 0 10303 214 }'));\nENDSEC;\nDATA;\n#1=PRODUCT('Bracket','Bracket','',(#2));\n#3=MANIFOLD_SOLID_BREP('',#4);\nENDSEC;\nEND-ISO-10303-21;`;
  const { meta } = text.step(Buffer.from(s));
  assert.equal(meta.Author, "Joe");
  assert.equal(meta["Originating system"], "SolidWorks 2024");
  assert.equal(meta.Schema, "AUTOMOTIVE_DESIGN");
  assert.deepEqual(meta["Product names"], ["Bracket"]);
  assert.equal(meta.Solids, 1);
});

test("G-code slicer comments and embedded thumbnail", () => {
  const png = Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3]).toString("base64");
  const g = `; generated by PrusaSlicer 2.8\n; thumbnail begin 16x16 10\n; ${png}\n; thumbnail end\nG28\n; estimated printing time (normal mode) = 1h 23m\n; filament used [g] = 12.5\n; filament_type = PETG\n; layer_height = 0.2\n`;
  const r = text.gcode(Buffer.from(g));
  assert.equal(r.meta.Slicer, "PrusaSlicer 2.8");
  assert.equal(r.meta["Print time"], "1h 23m");
  assert.equal(r.meta["Filament (g)"], 12.5);
  assert.equal(r.meta.Material, "PETG");
  assert.equal(r.image[0], 0x89);
});

test("KiCad PCB counts footprints and board size", () => {
  const pcb = `(kicad_pcb (version 20240108)\n(layers (0 "F.Cu" signal) (31 "B.Cu" signal))\n(net 0 "") (net 1 "GND")\n(footprint "R_0603" (property "Reference" "R1"))\n(footprint "C_0603" (property "Reference" "C1"))\n(gr_line (start 0 0) (end 50 0) (layer "Edge.Cuts"))\n(gr_line (start 50 0) (end 50 30) (layer "Edge.Cuts"))\n(segment (start 1 1) (end 2 2))\n)`;
  const { meta } = text.kicadPcb(Buffer.from(pcb));
  assert.equal(meta.Footprints, 2);
  assert.equal(meta["Copper layers"], 2);
  assert.equal(meta.Nets, 1);
  assert.equal(meta["Board width (mm)"], 50);
  assert.equal(meta["Board height (mm)"], 30);
});
