// Text-based engineering formats: STEP, DXF, G-code, KiCad, plain text.
function step(buf) {
  const head = buf.subarray(0, 64 * 1024).toString("latin1");
  const meta = { Format: "STEP" };
  const fd = head.match(/FILE_DESCRIPTION\s*\(\s*\(\s*'([^']*)'/);
  if (fd && fd[1]) meta.Description = fd[1];
  const fn = head.match(/FILE_NAME\s*\(\s*'([^']*)'\s*,\s*'([^']*)'\s*,\s*\(\s*'([^']*)'[^)]*\)\s*,\s*\(\s*'([^']*)'[^)]*\)\s*,\s*'([^']*)'\s*,\s*'([^']*)'/);
  if (fn) {
    if (fn[2]) meta.Timestamp = fn[2];
    if (fn[3]) meta.Author = fn[3];
    if (fn[4]) meta.Organization = fn[4];
    if (fn[6]) meta["Originating system"] = fn[6];
  }
  const schema = head.match(/FILE_SCHEMA\s*\(\s*\(\s*'([^']*)'/);
  if (schema) meta.Schema = schema[1].split(/[\s{]/)[0];
  const text = buf.toString("latin1");
  const products = [...text.matchAll(/=\s*PRODUCT\s*\(\s*'([^']*)'/g)].map((m) => m[1]);
  if (products.length) {
    meta.Products = products.length;
    meta["Product names"] = [...new Set(products)].slice(0, 30);
  }
  meta.Solids = (text.match(/MANIFOLD_SOLID_BREP/g) || []).length;
  meta.Faces = (text.match(/ADVANCED_FACE/g) || []).length;
  return { meta };
}

function dxf(buf) {
  const text = buf.toString("latin1");
  const lines = text.split(/\r?\n/);
  const meta = { Format: "DXF" };
  const layers = new Set();
  const types = {};
  let section = "";
  for (let i = 0; i < lines.length - 1; i += 2) {
    const code = lines[i].trim(), val = lines[i + 1].trim();
    if (code === "2" && lines[i - 1] && lines[i - 1].trim() === "SECTION") section = val;
    else if (code === "0" && val === "SECTION") section = (lines[i + 3] || "").trim();
    if (section === "ENTITIES" && code === "0" && val !== "SECTION" && val !== "ENDSEC") types[val] = (types[val] || 0) + 1;
    if (code === "8") layers.add(val);
    if (code === "9" && val === "$ACADVER") meta["AutoCAD version"] = (lines[i + 3] || "").trim();
  }
  meta.Layers = layers.size;
  const ents = Object.entries(types).sort((a, b) => b[1] - a[1]);
  meta.Entities = ents.reduce((s, e) => s + e[1], 0);
  if (ents.length) meta["Entity types"] = Object.fromEntries(ents.slice(0, 8));
  return { meta };
}

// Slicer G-code: settings live in ';' comments. PrusaSlicer/OrcaSlicer/Bambu
// embed a base64 PNG thumbnail block; Cura writes ';FLAVOR' and ';TIME'.
function gcode(buf) {
  const text = buf.toString("latin1");
  const meta = { Format: "G-code" };
  const grab = (re, label, fn = (v) => v) => {
    const m = text.match(re);
    if (m) meta[label] = fn(m[1].trim());
  };
  grab(/;\s*generated by\s+([^\n]+)/i, "Slicer");
  grab(/;\s*(?:FLAVOR):\s*([^\n]+)/i, "Flavor");
  grab(/;\s*estimated printing time[^=]*=\s*([^\n]+)/i, "Print time");
  grab(/;\s*TIME:\s*(\d+)/i, "Print time", (s) => secondsToText(+s));
  grab(/;\s*(?:total )?filament used \[mm\]\s*=\s*([^\n]+)/i, "Filament (mm)", (s) => Math.round(+s));
  grab(/;\s*filament used \[g\]\s*=\s*([^\n]+)/i, "Filament (g)", (s) => +s);
  grab(/;\s*Filament used:\s*([^\n]+)/i, "Filament", (s) => s);
  grab(/;\s*filament_type\s*=\s*([^\n]+)/i, "Material");
  grab(/;\s*layer_height\s*=\s*([^\n]+)/i, "Layer height");
  grab(/;\s*Layer height:\s*([^\n]+)/i, "Layer height");
  grab(/;\s*nozzle_diameter\s*=\s*([^\n]+)/i, "Nozzle");
  grab(/;\s*printer_model\s*=\s*([^\n]+)/i, "Printer");
  grab(/;\s*printer_settings_id\s*=\s*([^\n]+)/i, "Printer profile");
  grab(/;\s*fill_density\s*=\s*([^\n]+)/i, "Infill");
  grab(/;\s*temperature\s*=\s*([^\n]+)/i, "Nozzle temp");
  grab(/;\s*bed_temperature\s*=\s*([^\n]+)/i, "Bed temp");
  grab(/;\s*total layer number:\s*(\d+)/i, "Layers", Number);
  grab(/;\s*LAYER_COUNT:\s*(\d+)/i, "Layers", Number);
  grab(/;\s*MINX:\s*([^\n]+)/i, "Min X", Number);
  grab(/;\s*MAXX:\s*([^\n]+)/i, "Max X", Number);
  let image = null;
  const th = text.match(/; thumbnail begin[^\n]*\n([\s\S]*?); thumbnail end/gi);
  if (th) {
    // pick the largest embedded thumbnail
    let best = "";
    for (const block of th) {
      const b64 = block.split("\n").slice(1, -1).map((l) => l.replace(/^;\s?/, "").trim()).join("");
      if (b64.length > best.length) best = b64;
    }
    if (best) image = Buffer.from(best, "base64");
  }
  return { image, meta };
}

function secondsToText(s) {
  const h = Math.floor(s / 3600), m = Math.round((s % 3600) / 60);
  return h ? `${h}h ${m}m` : `${m}m`;
}

function kicadPcb(buf) {
  const text = buf.toString("utf8");
  const meta = { Format: "KiCad PCB" };
  meta.Footprints = (text.match(/\(footprint\s/g) || []).length;
  meta.Nets = Math.max(0, (text.match(/\(net\s+\d+\s/g) || []).length - 1);
  meta.Tracks = (text.match(/\(segment\s/g) || []).length;
  meta.Vias = (text.match(/\(via\s/g) || []).length;
  const ls = text.indexOf("(layers");
  if (ls >= 0) {
    const le = [text.indexOf("(setup", ls), text.indexOf("(net ", ls)].filter((i) => i > 0);
    const block = text.slice(ls, le.length ? Math.min(...le) : ls + 4000);
    meta["Copper layers"] = (block.match(/\.Cu"/g) || []).length;
  }
  const ver = text.match(/\(version\s+(\d+)\)/);
  if (ver) meta["File version"] = ver[1];
  const refs = [...text.matchAll(/\(property\s+"Reference"\s+"([^"]+)"/g)].map((m) => m[1]);
  if (refs.length) meta["References"] = refs.slice(0, 60);
  // board outline bbox from Edge.Cuts lines
  const xs = [], ys = [];
  for (const m of text.matchAll(/\(gr_(?:line|arc|rect|circle)[\s\S]*?\(layer\s+"Edge\.Cuts"\)/g)) {
    for (const p of m[0].matchAll(/\((?:start|end|center|mid)\s+([-\d.]+)\s+([-\d.]+)\)/g)) {
      xs.push(+p[1]);
      ys.push(+p[2]);
    }
  }
  if (xs.length) {
    meta["Board width (mm)"] = round2(Math.max(...xs) - Math.min(...xs));
    meta["Board height (mm)"] = round2(Math.max(...ys) - Math.min(...ys));
  }
  return { meta, text: refs.join(" ") };
}

function kicadSch(buf) {
  const text = buf.toString("utf8");
  const meta = { Format: "KiCad schematic" };
  meta.Symbols = (text.match(/\(symbol\s+\(lib_id/g) || []).length;
  meta.Wires = (text.match(/\(wire\s/g) || []).length;
  meta.Labels = (text.match(/\((?:global_)?label\s/g) || []).length;
  const values = [...text.matchAll(/\(property\s+"Value"\s+"([^"]+)"/g)].map((m) => m[1]);
  return { meta, text: values.join(" ") };
}

function plain(buf) {
  const text = buf.subarray(0, 200000).toString("utf8");
  return { meta: { Lines: text.split(/\r?\n/).length, Characters: text.length }, text };
}

function round2(v) {
  return Math.round(v * 100) / 100;
}

module.exports = { step, dxf, gcode, kicadPcb, kicadSch, plain };
